### ISSUE TITLE
请问如何更换主题

### ISSUE THREAD

**Issue by Makebignew** [MoeYi/netlify-hexo#2]
在配置文件里修改主题为 material 然后部署会出现page not found，不知道怎么回事，改成默认的next就一切正常，但是我看到theme文件夹里是有material 主题的

**Comment by clansty** [comment]
这说明你是直接 cd 到 themes 文件夹然后把主题 clone 下来的。你需要下载主题 zip，解压进去，直接 clone 会变成 git 子模块从而出现错误。

很抱歉没看到你的 issue

**Comment by clansty** [comment]
另外主题是需要配置的，里面自带的主题好久没更新了，建议重新下载主题并安装

**Comment by Makebignew** [comment]
谢谢，现在没问题了😁

2018年2月23日 下午9:59，"MoeYi" <notifications@github.com>寫道：
